<?php
$data = array (
  807 => 
  array (
    'cat_id' => '807',
    'cat_name' => '坚果干果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '807',
    'name' => '坚果干果',
  ),
  808 => 
  array (
    'cat_id' => '808',
    'cat_name' => '基础营养',
    'measure_unit' => '',
    'parent_id' => '807',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '808',
    'name' => '基础营养',
  ),
  818 => 
  array (
    'cat_id' => '818',
    'cat_name' => '葡萄籽',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '818',
    'name' => '葡萄籽',
  ),
  814 => 
  array (
    'cat_id' => '814',
    'cat_name' => '蛋白粉',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '814',
    'name' => '蛋白粉',
  ),
  816 => 
  array (
    'cat_id' => '816',
    'cat_name' => '左旋肉碱',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '816',
    'name' => '左旋肉碱',
  ),
  812 => 
  array (
    'cat_id' => '812',
    'cat_name' => '膳食纤维',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '812',
    'name' => '膳食纤维',
  ),
  817 => 
  array (
    'cat_id' => '817',
    'cat_name' => '胶原蛋白',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '817',
    'name' => '胶原蛋白',
  ),
  813 => 
  array (
    'cat_id' => '813',
    'cat_name' => '螺旋藻',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '813',
    'name' => '螺旋藻',
  ),
  820 => 
  array (
    'cat_id' => '820',
    'cat_name' => '滋补养生',
    'measure_unit' => '',
    'parent_id' => '807',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '820',
    'name' => '滋补养生',
  ),
  825 => 
  array (
    'cat_id' => '825',
    'cat_name' => '更多滋补',
    'measure_unit' => '',
    'parent_id' => '820',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '825',
    'name' => '更多滋补',
  ),
  822 => 
  array (
    'cat_id' => '822',
    'cat_name' => '阿胶',
    'measure_unit' => '',
    'parent_id' => '820',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '822',
    'name' => '阿胶',
  ),
  827 => 
  array (
    'cat_id' => '827',
    'cat_name' => '干果',
    'measure_unit' => '',
    'parent_id' => '807',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '827',
    'name' => '干果',
  ),
  830 => 
  array (
    'cat_id' => '830',
    'cat_name' => '中老年',
    'measure_unit' => '',
    'parent_id' => '827',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '830',
    'name' => '中老年',
  ),
  831 => 
  array (
    'cat_id' => '831',
    'cat_name' => '新疆大枣',
    'measure_unit' => '',
    'parent_id' => '827',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '831',
    'name' => '新疆大枣',
  ),
  828 => 
  array (
    'cat_id' => '828',
    'cat_name' => '成年女性',
    'measure_unit' => '',
    'parent_id' => '827',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '828',
    'name' => '成年女性',
  ),
  854 => 
  array (
    'cat_id' => '854',
    'cat_name' => '特色工艺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '854',
    'name' => '特色工艺',
  ),
  880 => 
  array (
    'cat_id' => '880',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '880',
    'name' => '方便速食',
  ),
  883 => 
  array (
    'cat_id' => '883',
    'cat_name' => '速食罐头',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '883',
    'name' => '速食罐头',
  ),
  884 => 
  array (
    'cat_id' => '884',
    'cat_name' => '鱼子酱',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '884',
    'name' => '鱼子酱',
  ),
  881 => 
  array (
    'cat_id' => '881',
    'cat_name' => '速食面/汤',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '881',
    'name' => '速食面/汤',
  ),
  882 => 
  array (
    'cat_id' => '882',
    'cat_name' => '米粉/米线',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '882',
    'name' => '米粉/米线',
  ),
  872 => 
  array (
    'cat_id' => '872',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '872',
    'name' => '南北干货',
  ),
  876 => 
  array (
    'cat_id' => '876',
    'cat_name' => '干货礼盒',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '876',
    'name' => '干货礼盒',
  ),
  874 => 
  array (
    'cat_id' => '874',
    'cat_name' => '菜干',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '874',
    'name' => '菜干',
  ),
  878 => 
  array (
    'cat_id' => '878',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '878',
    'name' => '其他',
  ),
  875 => 
  array (
    'cat_id' => '875',
    'cat_name' => '木耳/银耳',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '875',
    'name' => '木耳/银耳',
  ),
  873 => 
  array (
    'cat_id' => '873',
    'cat_name' => '菌菇',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '873',
    'name' => '菌菇',
  ),
  879 => 
  array (
    'cat_id' => '879',
    'cat_name' => '海产干货',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '879',
    'name' => '海产干货',
  ),
  865 => 
  array (
    'cat_id' => '865',
    'cat_name' => '厨房调料',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '865',
    'name' => '厨房调料',
  ),
  870 => 
  array (
    'cat_id' => '870',
    'cat_name' => '果酱/涂抹酱',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '870',
    'name' => '果酱/涂抹酱',
  ),
  867 => 
  array (
    'cat_id' => '867',
    'cat_name' => '调味油/汁',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '867',
    'name' => '调味油/汁',
  ),
  868 => 
  array (
    'cat_id' => '868',
    'cat_name' => '调味料/粉/酱',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '868',
    'name' => '调味料/粉/酱',
  ),
  869 => 
  array (
    'cat_id' => '869',
    'cat_name' => '底料/汤料',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '869',
    'name' => '底料/汤料',
  ),
  866 => 
  array (
    'cat_id' => '866',
    'cat_name' => '酱油/醋',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '866',
    'name' => '酱油/醋',
  ),
  859 => 
  array (
    'cat_id' => '859',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '859',
    'name' => '米面杂粮',
  ),
  864 => 
  array (
    'cat_id' => '864',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '864',
    'name' => '礼盒',
  ),
  861 => 
  array (
    'cat_id' => '861',
    'cat_name' => '意大利面',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '861',
    'name' => '意大利面',
  ),
  862 => 
  array (
    'cat_id' => '862',
    'cat_name' => '面粉/面条',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '862',
    'name' => '面粉/面条',
  ),
  863 => 
  array (
    'cat_id' => '863',
    'cat_name' => '杂粮',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '863',
    'name' => '杂粮',
  ),
  860 => 
  array (
    'cat_id' => '860',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '860',
    'name' => '大米',
  ),
  855 => 
  array (
    'cat_id' => '855',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '855',
    'name' => '食用油',
  ),
  856 => 
  array (
    'cat_id' => '856',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '855',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '856',
    'name' => '橄榄油',
  ),
  857 => 
  array (
    'cat_id' => '857',
    'cat_name' => '其他食用油',
    'measure_unit' => '',
    'parent_id' => '855',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '857',
    'name' => '其他食用油',
  ),
  948 => 
  array (
    'cat_id' => '948',
    'cat_name' => '古玩玉器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '948',
    'name' => '古玩玉器',
  ),
  949 => 
  array (
    'cat_id' => '949',
    'cat_name' => '大枣',
    'measure_unit' => '',
    'parent_id' => '948',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '949',
    'name' => '大枣',
  ),
  885 => 
  array (
    'cat_id' => '885',
    'cat_name' => '粮油副食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '885',
    'name' => '粮油副食',
  ),
  909 => 
  array (
    'cat_id' => '909',
    'cat_name' => '水具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '909',
    'name' => '水具',
  ),
  914 => 
  array (
    'cat_id' => '914',
    'cat_name' => '运动水壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '914',
    'name' => '运动水壶',
  ),
  913 => 
  array (
    'cat_id' => '913',
    'cat_name' => '保温杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '913',
    'name' => '保温杯/壶',
  ),
  912 => 
  array (
    'cat_id' => '912',
    'cat_name' => '陶瓷杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '912',
    'name' => '陶瓷杯/壶',
  ),
  910 => 
  array (
    'cat_id' => '910',
    'cat_name' => '塑料杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '910',
    'name' => '塑料杯/壶',
  ),
  911 => 
  array (
    'cat_id' => '911',
    'cat_name' => '玻璃杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '911',
    'name' => '玻璃杯/壶',
  ),
  886 => 
  array (
    'cat_id' => '886',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '886',
    'name' => '烹饪锅具',
  ),
  892 => 
  array (
    'cat_id' => '892',
    'cat_name' => '烧水壶',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '892',
    'name' => '烧水壶',
  ),
  889 => 
  array (
    'cat_id' => '889',
    'cat_name' => '汤锅/奶锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '889',
    'name' => '汤锅/奶锅',
  ),
  893 => 
  array (
    'cat_id' => '893',
    'cat_name' => '砂锅/石锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '893',
    'name' => '砂锅/石锅',
  ),
  890 => 
  array (
    'cat_id' => '890',
    'cat_name' => '蒸锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '890',
    'name' => '蒸锅',
  ),
  887 => 
  array (
    'cat_id' => '887',
    'cat_name' => '炒锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '887',
    'name' => '炒锅',
  ),
  891 => 
  array (
    'cat_id' => '891',
    'cat_name' => '锅具套装',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '891',
    'name' => '锅具套装',
  ),
  888 => 
  array (
    'cat_id' => '888',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '888',
    'name' => '煎锅',
  ),
  902 => 
  array (
    'cat_id' => '902',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '902',
    'name' => '餐具',
  ),
  906 => 
  array (
    'cat_id' => '906',
    'cat_name' => '咖啡器具',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '906',
    'name' => '咖啡器具',
  ),
  907 => 
  array (
    'cat_id' => '907',
    'cat_name' => '烧烤用具',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '907',
    'name' => '烧烤用具',
  ),
  904 => 
  array (
    'cat_id' => '904',
    'cat_name' => '茶具/配件',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '904',
    'name' => '茶具/配件',
  ),
  903 => 
  array (
    'cat_id' => '903',
    'cat_name' => '碗/盘/碟/套装',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '903',
    'name' => '碗/盘/碟/套装',
  ),
  908 => 
  array (
    'cat_id' => '908',
    'cat_name' => '其他餐具配件',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '908',
    'name' => '其他餐具配件',
  ),
  905 => 
  array (
    'cat_id' => '905',
    'cat_name' => '酒具/配件',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '905',
    'name' => '酒具/配件',
  ),
  894 => 
  array (
    'cat_id' => '894',
    'cat_name' => '厨房用具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '894',
    'name' => '厨房用具',
  ),
  899 => 
  array (
    'cat_id' => '899',
    'cat_name' => '烘焙用具',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '899',
    'name' => '烘焙用具',
  ),
  896 => 
  array (
    'cat_id' => '896',
    'cat_name' => '保鲜盒',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '896',
    'name' => '保鲜盒',
  ),
  900 => 
  array (
    'cat_id' => '900',
    'cat_name' => '清洁用具',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '900',
    'name' => '清洁用具',
  ),
  897 => 
  array (
    'cat_id' => '897',
    'cat_name' => '密器罐/调味瓶',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '897',
    'name' => '密器罐/调味瓶',
  ),
  901 => 
  array (
    'cat_id' => '901',
    'cat_name' => '其他厨房配件',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '901',
    'name' => '其他厨房配件',
  ),
  898 => 
  array (
    'cat_id' => '898',
    'cat_name' => '保鲜膜/袋',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '898',
    'name' => '保鲜膜/袋',
  ),
  895 => 
  array (
    'cat_id' => '895',
    'cat_name' => '刀具',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '895',
    'name' => '刀具',
  ),
  915 => 
  array (
    'cat_id' => '915',
    'cat_name' => '婴儿喂养用品',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '915',
    'name' => '婴儿喂养用品',
  ),
  916 => 
  array (
    'cat_id' => '916',
    'cat_name' => '奶瓶',
    'measure_unit' => '',
    'parent_id' => '915',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '916',
    'name' => '奶瓶',
  ),
  919 => 
  array (
    'cat_id' => '919',
    'cat_name' => '宝宝餐具',
    'measure_unit' => '',
    'parent_id' => '915',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '919',
    'name' => '宝宝餐具',
  ),
  920 => 
  array (
    'cat_id' => '920',
    'cat_name' => '其他辅助工具',
    'measure_unit' => '',
    'parent_id' => '915',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '920',
    'name' => '其他辅助工具',
  ),
  733 => 
  array (
    'cat_id' => '733',
    'cat_name' => '水果鲜果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '733',
    'name' => '水果鲜果',
  ),
  744 => 
  array (
    'cat_id' => '744',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '744',
    'name' => '葡萄酒',
  ),
  747 => 
  array (
    'cat_id' => '747',
    'cat_name' => '桃红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '747',
    'name' => '桃红葡萄酒',
  ),
  751 => 
  array (
    'cat_id' => '751',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '751',
    'name' => '礼盒',
  ),
  748 => 
  array (
    'cat_id' => '748',
    'cat_name' => '香槟/起泡酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '748',
    'name' => '香槟/起泡酒',
  ),
  745 => 
  array (
    'cat_id' => '745',
    'cat_name' => '红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '745',
    'name' => '红葡萄酒',
  ),
  749 => 
  array (
    'cat_id' => '749',
    'cat_name' => '甜酒/贵腐酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '749',
    'name' => '甜酒/贵腐酒',
  ),
  746 => 
  array (
    'cat_id' => '746',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '746',
    'name' => '白葡萄酒',
  ),
  750 => 
  array (
    'cat_id' => '750',
    'cat_name' => '加强型葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '750',
    'name' => '加强型葡萄酒',
  ),
  760 => 
  array (
    'cat_id' => '760',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '760',
    'name' => '啤酒',
  ),
  763 => 
  array (
    'cat_id' => '763',
    'cat_name' => '白啤',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '763',
    'name' => '白啤',
  ),
  764 => 
  array (
    'cat_id' => '764',
    'cat_name' => '果味啤酒',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '764',
    'name' => '果味啤酒',
  ),
  761 => 
  array (
    'cat_id' => '761',
    'cat_name' => '黑啤',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '761',
    'name' => '黑啤',
  ),
  765 => 
  array (
    'cat_id' => '765',
    'cat_name' => '量贩装啤酒',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '765',
    'name' => '量贩装啤酒',
  ),
  762 => 
  array (
    'cat_id' => '762',
    'cat_name' => '黄啤',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '762',
    'name' => '黄啤',
  ),
  775 => 
  array (
    'cat_id' => '775',
    'cat_name' => '饮料/水',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '775',
    'name' => '饮料/水',
  ),
  780 => 
  array (
    'cat_id' => '780',
    'cat_name' => '咖啡饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '780',
    'name' => '咖啡饮料',
  ),
  777 => 
  array (
    'cat_id' => '777',
    'cat_name' => '果蔬饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '777',
    'name' => '果蔬饮料',
  ),
  778 => 
  array (
    'cat_id' => '778',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '778',
    'name' => '茶饮料',
  ),
  779 => 
  array (
    'cat_id' => '779',
    'cat_name' => '水',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '779',
    'name' => '水',
  ),
  776 => 
  array (
    'cat_id' => '776',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '776',
    'name' => '碳酸饮料',
  ),
  752 => 
  array (
    'cat_id' => '752',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '752',
    'name' => '洋酒',
  ),
  757 => 
  array (
    'cat_id' => '757',
    'cat_name' => '朗姆酒',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '757',
    'name' => '朗姆酒',
  ),
  754 => 
  array (
    'cat_id' => '754',
    'cat_name' => '伏特加',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '754',
    'name' => '伏特加',
  ),
  758 => 
  array (
    'cat_id' => '758',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '758',
    'name' => '其他',
  ),
  755 => 
  array (
    'cat_id' => '755',
    'cat_name' => '白兰地',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '755',
    'name' => '白兰地',
  ),
  759 => 
  array (
    'cat_id' => '759',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '759',
    'name' => '礼盒',
  ),
  756 => 
  array (
    'cat_id' => '756',
    'cat_name' => '利口酒',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '756',
    'name' => '利口酒',
  ),
  753 => 
  array (
    'cat_id' => '753',
    'cat_name' => '威士忌',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '753',
    'name' => '威士忌',
  ),
  769 => 
  array (
    'cat_id' => '769',
    'cat_name' => '牛奶乳品',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '769',
    'name' => '牛奶乳品',
  ),
  774 => 
  array (
    'cat_id' => '774',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '774',
    'name' => '礼盒',
  ),
  770 => 
  array (
    'cat_id' => '770',
    'cat_name' => '牛奶',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '770',
    'name' => '牛奶',
  ),
  771 => 
  array (
    'cat_id' => '771',
    'cat_name' => '豆奶',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '771',
    'name' => '豆奶',
  ),
  772 => 
  array (
    'cat_id' => '772',
    'cat_name' => '低温奶',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '772',
    'name' => '低温奶',
  ),
  734 => 
  array (
    'cat_id' => '734',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '734',
    'name' => '白酒',
  ),
  741 => 
  array (
    'cat_id' => '741',
    'cat_name' => '汾酒',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '741',
    'name' => '汾酒',
  ),
  738 => 
  array (
    'cat_id' => '738',
    'cat_name' => '洋河',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '738',
    'name' => '洋河',
  ),
  735 => 
  array (
    'cat_id' => '735',
    'cat_name' => '茅台',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '735',
    'name' => '茅台',
  ),
  742 => 
  array (
    'cat_id' => '742',
    'cat_name' => '牛栏山',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '742',
    'name' => '牛栏山',
  ),
  739 => 
  array (
    'cat_id' => '739',
    'cat_name' => '郎酒',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '739',
    'name' => '郎酒',
  ),
  736 => 
  array (
    'cat_id' => '736',
    'cat_name' => '五粮液',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '736',
    'name' => '五粮液',
  ),
  743 => 
  array (
    'cat_id' => '743',
    'cat_name' => '其他品牌',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '743',
    'name' => '其他品牌',
  ),
  740 => 
  array (
    'cat_id' => '740',
    'cat_name' => '泸州老窖',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '740',
    'name' => '泸州老窖',
  ),
  737 => 
  array (
    'cat_id' => '737',
    'cat_name' => '剑南春',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '737',
    'name' => '剑南春',
  ),
  766 => 
  array (
    'cat_id' => '766',
    'cat_name' => '其他酒品',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '766',
    'name' => '其他酒品',
  ),
  767 => 
  array (
    'cat_id' => '767',
    'cat_name' => '黄酒',
    'measure_unit' => '',
    'parent_id' => '766',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '767',
    'name' => '黄酒',
  ),
  768 => 
  array (
    'cat_id' => '768',
    'cat_name' => '养生酒',
    'measure_unit' => '',
    'parent_id' => '766',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '768',
    'name' => '养生酒',
  ),
  832 => 
  array (
    'cat_id' => '832',
    'cat_name' => '零食 饼干',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '832',
    'name' => '零食 饼干',
  ),
  833 => 
  array (
    'cat_id' => '833',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '833',
    'name' => '休闲零食',
  ),
  838 => 
  array (
    'cat_id' => '838',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '833',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '838',
    'name' => '果冻',
  ),
  836 => 
  array (
    'cat_id' => '836',
    'cat_name' => '蜜饯',
    'measure_unit' => '',
    'parent_id' => '833',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '836',
    'name' => '蜜饯',
  ),
  837 => 
  array (
    'cat_id' => '837',
    'cat_name' => '肉类零食',
    'measure_unit' => '',
    'parent_id' => '833',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '837',
    'name' => '肉类零食',
  ),
  847 => 
  array (
    'cat_id' => '847',
    'cat_name' => '糕点/烘焙',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '847',
    'name' => '糕点/烘焙',
  ),
  853 => 
  array (
    'cat_id' => '853',
    'cat_name' => '沙琪玛',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '853',
    'name' => '沙琪玛',
  ),
  850 => 
  array (
    'cat_id' => '850',
    'cat_name' => '蛋卷/松塔',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '850',
    'name' => '蛋卷/松塔',
  ),
  851 => 
  array (
    'cat_id' => '851',
    'cat_name' => '蛋糕/派',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '851',
    'name' => '蛋糕/派',
  ),
  848 => 
  array (
    'cat_id' => '848',
    'cat_name' => '马卡龙',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '848',
    'name' => '马卡龙',
  ),
  852 => 
  array (
    'cat_id' => '852',
    'cat_name' => '传统糕点',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '852',
    'name' => '传统糕点',
  ),
  849 => 
  array (
    'cat_id' => '849',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '849',
    'name' => '面包',
  ),
  843 => 
  array (
    'cat_id' => '843',
    'cat_name' => '曲奇/饼干',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '843',
    'name' => '曲奇/饼干',
  ),
  844 => 
  array (
    'cat_id' => '844',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '843',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '844',
    'name' => '曲奇',
  ),
  845 => 
  array (
    'cat_id' => '845',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '843',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '845',
    'name' => '饼干',
  ),
  840 => 
  array (
    'cat_id' => '840',
    'cat_name' => '糖果/巧克力',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '840',
    'name' => '糖果/巧克力',
  ),
  841 => 
  array (
    'cat_id' => '841',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '840',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '841',
    'name' => '巧克力',
  ),
  842 => 
  array (
    'cat_id' => '842',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '840',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '842',
    'name' => '糖果',
  ),
  921 => 
  array (
    'cat_id' => '921',
    'cat_name' => '母婴食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '921',
    'name' => '母婴食品',
  ),
  931 => 
  array (
    'cat_id' => '931',
    'cat_name' => '辅食',
    'measure_unit' => '',
    'parent_id' => '921',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '931',
    'name' => '辅食',
  ),
  934 => 
  array (
    'cat_id' => '934',
    'cat_name' => '面条类',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '934',
    'name' => '面条类',
  ),
  938 => 
  array (
    'cat_id' => '938',
    'cat_name' => '宝宝零食',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '938',
    'name' => '宝宝零食',
  ),
  935 => 
  array (
    'cat_id' => '935',
    'cat_name' => '肉松/肉绒/肉酥',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '935',
    'name' => '肉松/肉绒/肉酥',
  ),
  932 => 
  array (
    'cat_id' => '932',
    'cat_name' => '果泥/肉泥/菜泥',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '932',
    'name' => '果泥/肉泥/菜泥',
  ),
  936 => 
  array (
    'cat_id' => '936',
    'cat_name' => '果汁/水/奶',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '936',
    'name' => '果汁/水/奶',
  ),
  933 => 
  array (
    'cat_id' => '933',
    'cat_name' => '米粉/米糊/冲调类',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '933',
    'name' => '米粉/米糊/冲调类',
  ),
  937 => 
  array (
    'cat_id' => '937',
    'cat_name' => '长牙期食品',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '937',
    'name' => '长牙期食品',
  ),
  922 => 
  array (
    'cat_id' => '922',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '921',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '922',
    'name' => '奶粉',
  ),
  928 => 
  array (
    'cat_id' => '928',
    'cat_name' => '四段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '928',
    'name' => '四段奶粉',
  ),
  925 => 
  array (
    'cat_id' => '925',
    'cat_name' => '一段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '925',
    'name' => '一段奶粉',
  ),
  929 => 
  array (
    'cat_id' => '929',
    'cat_name' => '特殊配方奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '929',
    'name' => '特殊配方奶粉',
  ),
  926 => 
  array (
    'cat_id' => '926',
    'cat_name' => '二段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '926',
    'name' => '二段奶粉',
  ),
  923 => 
  array (
    'cat_id' => '923',
    'cat_name' => '国外有机奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '923',
    'name' => '国外有机奶粉',
  ),
  930 => 
  array (
    'cat_id' => '930',
    'cat_name' => '孕妇奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '930',
    'name' => '孕妇奶粉',
  ),
  927 => 
  array (
    'cat_id' => '927',
    'cat_name' => '三段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '927',
    'name' => '三段奶粉',
  ),
  924 => 
  array (
    'cat_id' => '924',
    'cat_name' => '羊奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '924',
    'name' => '羊奶粉',
  ),
  939 => 
  array (
    'cat_id' => '939',
    'cat_name' => '营养品',
    'measure_unit' => '',
    'parent_id' => '921',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '939',
    'name' => '营养品',
  ),
  947 => 
  array (
    'cat_id' => '947',
    'cat_name' => '孕产营养品',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '947',
    'name' => '孕产营养品',
  ),
  944 => 
  array (
    'cat_id' => '944',
    'cat_name' => '维生素/葡萄糖',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '944',
    'name' => '维生素/葡萄糖',
  ),
  941 => 
  array (
    'cat_id' => '941',
    'cat_name' => 'DHA',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '941',
    'name' => 'DHA',
  ),
  945 => 
  array (
    'cat_id' => '945',
    'cat_name' => '清火/开胃/伴侣',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '945',
    'name' => '清火/开胃/伴侣',
  ),
  942 => 
  array (
    'cat_id' => '942',
    'cat_name' => '益生菌',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '942',
    'name' => '益生菌',
  ),
  946 => 
  array (
    'cat_id' => '946',
    'cat_name' => '孕婴食用油',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '946',
    'name' => '孕婴食用油',
  ),
  943 => 
  array (
    'cat_id' => '943',
    'cat_name' => '鱼肝油',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '943',
    'name' => '鱼肝油',
  ),
  940 => 
  array (
    'cat_id' => '940',
    'cat_name' => '钙铁锌/乳铁蛋白/初乳',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '940',
    'name' => '钙铁锌/乳铁蛋白/初乳',
  ),
  950 => 
  array (
    'cat_id' => '950',
    'cat_name' => '肉食制品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '950',
    'name' => '肉食制品',
  ),
  683 => 
  array (
    'cat_id' => '683',
    'cat_name' => '营业保健',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '683',
    'name' => '营业保健',
  ),
  731 => 
  array (
    'cat_id' => '731',
    'cat_name' => '速食冰品',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '731',
    'name' => '速食冰品',
  ),
  721 => 
  array (
    'cat_id' => '721',
    'cat_name' => '肉类熟食',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '721',
    'name' => '肉类熟食',
  ),
  724 => 
  array (
    'cat_id' => '724',
    'cat_name' => '培根',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '724',
    'name' => '培根',
  ),
  725 => 
  array (
    'cat_id' => '725',
    'cat_name' => '其他熟食',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '725',
    'name' => '其他熟食',
  ),
  722 => 
  array (
    'cat_id' => '722',
    'cat_name' => '香肠',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '722',
    'name' => '香肠',
  ),
  723 => 
  array (
    'cat_id' => '723',
    'cat_name' => '火腿',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '723',
    'name' => '火腿',
  ),
  690 => 
  array (
    'cat_id' => '690',
    'cat_name' => '精品肉类',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '690',
    'name' => '精品肉类',
  ),
  695 => 
  array (
    'cat_id' => '695',
    'cat_name' => '肉类礼盒',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '695',
    'name' => '肉类礼盒',
  ),
  692 => 
  array (
    'cat_id' => '692',
    'cat_name' => '牛肉',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '692',
    'name' => '牛肉',
  ),
  691 => 
  array (
    'cat_id' => '691',
    'cat_name' => '猪肉',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '691',
    'name' => '猪肉',
  ),
  696 => 
  array (
    'cat_id' => '696',
    'cat_name' => '腌腊肉品',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '696',
    'name' => '腌腊肉品',
  ),
  697 => 
  array (
    'cat_id' => '697',
    'cat_name' => '海鲜水产',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '697',
    'name' => '海鲜水产',
  ),
  699 => 
  array (
    'cat_id' => '699',
    'cat_name' => '虾',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '699',
    'name' => '虾',
  ),
  703 => 
  array (
    'cat_id' => '703',
    'cat_name' => '水产礼盒',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '703',
    'name' => '水产礼盒',
  ),
  700 => 
  array (
    'cat_id' => '700',
    'cat_name' => '蟹/贝',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '700',
    'name' => '蟹/贝',
  ),
  701 => 
  array (
    'cat_id' => '701',
    'cat_name' => '参鲍',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '701',
    'name' => '参鲍',
  ),
  698 => 
  array (
    'cat_id' => '698',
    'cat_name' => '鱼',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '698',
    'name' => '鱼',
  ),
  702 => 
  array (
    'cat_id' => '702',
    'cat_name' => '加工水产',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '702',
    'name' => '加工水产',
  ),
  728 => 
  array (
    'cat_id' => '728',
    'cat_name' => '礼品券',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '728',
    'name' => '礼品券',
  ),
  729 => 
  array (
    'cat_id' => '729',
    'cat_name' => '大闸蟹券',
    'measure_unit' => '',
    'parent_id' => '728',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '729',
    'name' => '大闸蟹券',
  ),
  705 => 
  array (
    'cat_id' => '705',
    'cat_name' => '蔬菜',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '705',
    'name' => '蔬菜',
  ),
  710 => 
  array (
    'cat_id' => '710',
    'cat_name' => '礼盒/券',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '710',
    'name' => '礼盒/券',
  ),
  707 => 
  array (
    'cat_id' => '707',
    'cat_name' => '精选蔬菜',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '707',
    'name' => '精选蔬菜',
  ),
  711 => 
  array (
    'cat_id' => '711',
    'cat_name' => '宅配',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '711',
    'name' => '宅配',
  ),
  708 => 
  array (
    'cat_id' => '708',
    'cat_name' => '豆制品',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '708',
    'name' => '豆制品',
  ),
  709 => 
  array (
    'cat_id' => '709',
    'cat_name' => '加工蔬菜',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '709',
    'name' => '加工蔬菜',
  ),
  706 => 
  array (
    'cat_id' => '706',
    'cat_name' => '有机蔬菜',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '706',
    'name' => '有机蔬菜',
  ),
  717 => 
  array (
    'cat_id' => '717',
    'cat_name' => '蛋品',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '717',
    'name' => '蛋品',
  ),
  718 => 
  array (
    'cat_id' => '718',
    'cat_name' => '鸡蛋',
    'measure_unit' => '',
    'parent_id' => '717',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '718',
    'name' => '鸡蛋',
  ),
  719 => 
  array (
    'cat_id' => '719',
    'cat_name' => '松花蛋/咸鸭蛋',
    'measure_unit' => '',
    'parent_id' => '717',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '719',
    'name' => '松花蛋/咸鸭蛋',
  ),
  720 => 
  array (
    'cat_id' => '720',
    'cat_name' => '其他蛋类',
    'measure_unit' => '',
    'parent_id' => '717',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '720',
    'name' => '其他蛋类',
  ),
  684 => 
  array (
    'cat_id' => '684',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '684',
    'name' => '水果',
  ),
  685 => 
  array (
    'cat_id' => '685',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '685',
    'name' => '进口水果',
  ),
  689 => 
  array (
    'cat_id' => '689',
    'cat_name' => '冷冻水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '689',
    'name' => '冷冻水果',
  ),
  688 => 
  array (
    'cat_id' => '688',
    'cat_name' => '原产地水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '688',
    'name' => '原产地水果',
  ),
  686 => 
  array (
    'cat_id' => '686',
    'cat_name' => '国产水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '686',
    'name' => '国产水果',
  ),
  687 => 
  array (
    'cat_id' => '687',
    'cat_name' => '水果礼盒',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '687',
    'name' => '水果礼盒',
  ),
  713 => 
  array (
    'cat_id' => '713',
    'cat_name' => '冷藏奶品饮品',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '713',
    'name' => '冷藏奶品饮品',
  ),
  714 => 
  array (
    'cat_id' => '714',
    'cat_name' => '奶制品',
    'measure_unit' => '',
    'parent_id' => '713',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '714',
    'name' => '奶制品',
  ),
  715 => 
  array (
    'cat_id' => '715',
    'cat_name' => '低温奶',
    'measure_unit' => '',
    'parent_id' => '713',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '715',
    'name' => '低温奶',
  ),
  716 => 
  array (
    'cat_id' => '716',
    'cat_name' => '冷藏果汁',
    'measure_unit' => '',
    'parent_id' => '713',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '716',
    'name' => '冷藏果汁',
  ),
  782 => 
  array (
    'cat_id' => '782',
    'cat_name' => '冲调茶饮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '782',
    'name' => '冲调茶饮',
  ),
  799 => 
  array (
    'cat_id' => '799',
    'cat_name' => '国产茗茶',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '799',
    'name' => '国产茗茶',
  ),
  802 => 
  array (
    'cat_id' => '802',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '802',
    'name' => '白茶',
  ),
  806 => 
  array (
    'cat_id' => '806',
    'cat_name' => '其他国产茗茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '806',
    'name' => '其他国产茗茶',
  ),
  803 => 
  array (
    'cat_id' => '803',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '803',
    'name' => '乌龙茶',
  ),
  800 => 
  array (
    'cat_id' => '800',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '800',
    'name' => '绿茶',
  ),
  804 => 
  array (
    'cat_id' => '804',
    'cat_name' => '黑茶/普洱茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '804',
    'name' => '黑茶/普洱茶',
  ),
  801 => 
  array (
    'cat_id' => '801',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '801',
    'name' => '红茶',
  ),
  795 => 
  array (
    'cat_id' => '795',
    'cat_name' => '进口茶',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '795',
    'name' => '进口茶',
  ),
  797 => 
  array (
    'cat_id' => '797',
    'cat_name' => '花茶/果茶',
    'measure_unit' => '',
    'parent_id' => '795',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '797',
    'name' => '花茶/果茶',
  ),
  796 => 
  array (
    'cat_id' => '796',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '795',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '796',
    'name' => '红茶',
  ),
  783 => 
  array (
    'cat_id' => '783',
    'cat_name' => '休闲冲饮',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '783',
    'name' => '休闲冲饮',
  ),
  788 => 
  array (
    'cat_id' => '788',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '788',
    'name' => '奶茶',
  ),
  785 => 
  array (
    'cat_id' => '785',
    'cat_name' => '麦片/粥',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '785',
    'name' => '麦片/粥',
  ),
  789 => 
  array (
    'cat_id' => '789',
    'cat_name' => '天然谷物粉',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '789',
    'name' => '天然谷物粉',
  ),
  786 => 
  array (
    'cat_id' => '786',
    'cat_name' => '巧克力粉',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '786',
    'name' => '巧克力粉',
  ),
  787 => 
  array (
    'cat_id' => '787',
    'cat_name' => '养生/柚子茶',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '787',
    'name' => '养生/柚子茶',
  ),
  784 => 
  array (
    'cat_id' => '784',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '784',
    'name' => '蜂蜜',
  ),
  790 => 
  array (
    'cat_id' => '790',
    'cat_name' => '咖啡/伴侣',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '790',
    'name' => '咖啡/伴侣',
  ),
  794 => 
  array (
    'cat_id' => '794',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '794',
    'name' => '礼盒',
  ),
  791 => 
  array (
    'cat_id' => '791',
    'cat_name' => '速溶咖啡',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '791',
    'name' => '速溶咖啡',
  ),
  792 => 
  array (
    'cat_id' => '792',
    'cat_name' => '咖啡粉/豆',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '792',
    'name' => '咖啡粉/豆',
  ),
  793 => 
  array (
    'cat_id' => '793',
    'cat_name' => '调糖/伴侣',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '793',
    'name' => '调糖/伴侣',
  ),
);
?>