<?php
$data = array (
  0 => 
  array (
    'cat_id' => '807',
    'cat_name' => '坚果干果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '854',
    'cat_name' => '特色工艺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '948',
    'cat_name' => '古玩玉器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '885',
    'cat_name' => '粮油副食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '733',
    'cat_name' => '水果鲜果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '832',
    'cat_name' => '零食 饼干',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '921',
    'cat_name' => '母婴食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '950',
    'cat_name' => '肉食制品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '683',
    'cat_name' => '营业保健',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '782',
    'cat_name' => '冲调茶饮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '731',
    'cat_name' => '速食冰品',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '721',
    'cat_name' => '肉类熟食',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '690',
    'cat_name' => '精品肉类',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '697',
    'cat_name' => '海鲜水产',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '728',
    'cat_name' => '礼品券',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '705',
    'cat_name' => '蔬菜',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '717',
    'cat_name' => '蛋品',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '684',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '713',
    'cat_name' => '冷藏奶品饮品',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '685',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '689',
    'cat_name' => '冷冻水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '688',
    'cat_name' => '原产地水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '686',
    'cat_name' => '国产水果',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '687',
    'cat_name' => '水果礼盒',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '695',
    'cat_name' => '肉类礼盒',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '692',
    'cat_name' => '牛肉',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '691',
    'cat_name' => '猪肉',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '696',
    'cat_name' => '腌腊肉品',
    'measure_unit' => '',
    'parent_id' => '690',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '699',
    'cat_name' => '虾',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '703',
    'cat_name' => '水产礼盒',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '700',
    'cat_name' => '蟹/贝',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '701',
    'cat_name' => '参鲍',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '698',
    'cat_name' => '鱼',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '702',
    'cat_name' => '加工水产',
    'measure_unit' => '',
    'parent_id' => '697',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '710',
    'cat_name' => '礼盒/券',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '707',
    'cat_name' => '精选蔬菜',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '711',
    'cat_name' => '宅配',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '708',
    'cat_name' => '豆制品',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '709',
    'cat_name' => '加工蔬菜',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '706',
    'cat_name' => '有机蔬菜',
    'measure_unit' => '',
    'parent_id' => '705',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '714',
    'cat_name' => '奶制品',
    'measure_unit' => '',
    'parent_id' => '713',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '715',
    'cat_name' => '低温奶',
    'measure_unit' => '',
    'parent_id' => '713',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '716',
    'cat_name' => '冷藏果汁',
    'measure_unit' => '',
    'parent_id' => '713',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '718',
    'cat_name' => '鸡蛋',
    'measure_unit' => '',
    'parent_id' => '717',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '719',
    'cat_name' => '松花蛋/咸鸭蛋',
    'measure_unit' => '',
    'parent_id' => '717',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '720',
    'cat_name' => '其他蛋类',
    'measure_unit' => '',
    'parent_id' => '717',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '724',
    'cat_name' => '培根',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '725',
    'cat_name' => '其他熟食',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '722',
    'cat_name' => '香肠',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '723',
    'cat_name' => '火腿',
    'measure_unit' => '',
    'parent_id' => '721',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '729',
    'cat_name' => '大闸蟹券',
    'measure_unit' => '',
    'parent_id' => '728',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '744',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '760',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '775',
    'cat_name' => '饮料/水',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '752',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '769',
    'cat_name' => '牛奶乳品',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '734',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '766',
    'cat_name' => '其他酒品',
    'measure_unit' => '',
    'parent_id' => '733',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '741',
    'cat_name' => '汾酒',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '738',
    'cat_name' => '洋河',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '735',
    'cat_name' => '茅台',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '742',
    'cat_name' => '牛栏山',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '739',
    'cat_name' => '郎酒',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '736',
    'cat_name' => '五粮液',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '743',
    'cat_name' => '其他品牌',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '740',
    'cat_name' => '泸州老窖',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '737',
    'cat_name' => '剑南春',
    'measure_unit' => '',
    'parent_id' => '734',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '747',
    'cat_name' => '桃红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '751',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '748',
    'cat_name' => '香槟/起泡酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '745',
    'cat_name' => '红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '749',
    'cat_name' => '甜酒/贵腐酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '746',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '750',
    'cat_name' => '加强型葡萄酒',
    'measure_unit' => '',
    'parent_id' => '744',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '757',
    'cat_name' => '朗姆酒',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '754',
    'cat_name' => '伏特加',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '758',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '755',
    'cat_name' => '白兰地',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '759',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '756',
    'cat_name' => '利口酒',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '753',
    'cat_name' => '威士忌',
    'measure_unit' => '',
    'parent_id' => '752',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '763',
    'cat_name' => '白啤',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '764',
    'cat_name' => '果味啤酒',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '761',
    'cat_name' => '黑啤',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '765',
    'cat_name' => '量贩装啤酒',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '762',
    'cat_name' => '黄啤',
    'measure_unit' => '',
    'parent_id' => '760',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '767',
    'cat_name' => '黄酒',
    'measure_unit' => '',
    'parent_id' => '766',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '768',
    'cat_name' => '养生酒',
    'measure_unit' => '',
    'parent_id' => '766',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '774',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '770',
    'cat_name' => '牛奶',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '771',
    'cat_name' => '豆奶',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '772',
    'cat_name' => '低温奶',
    'measure_unit' => '',
    'parent_id' => '769',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '780',
    'cat_name' => '咖啡饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '777',
    'cat_name' => '果蔬饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '778',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '779',
    'cat_name' => '水',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '776',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '775',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '799',
    'cat_name' => '国产茗茶',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '795',
    'cat_name' => '进口茶',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '783',
    'cat_name' => '休闲冲饮',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '790',
    'cat_name' => '咖啡/伴侣',
    'measure_unit' => '',
    'parent_id' => '782',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '788',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '785',
    'cat_name' => '麦片/粥',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '789',
    'cat_name' => '天然谷物粉',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '786',
    'cat_name' => '巧克力粉',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '787',
    'cat_name' => '养生/柚子茶',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '784',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '783',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '794',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '791',
    'cat_name' => '速溶咖啡',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '792',
    'cat_name' => '咖啡粉/豆',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '793',
    'cat_name' => '调糖/伴侣',
    'measure_unit' => '',
    'parent_id' => '790',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '797',
    'cat_name' => '花茶/果茶',
    'measure_unit' => '',
    'parent_id' => '795',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '796',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '795',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '802',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '806',
    'cat_name' => '其他国产茗茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '803',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '800',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '804',
    'cat_name' => '黑茶/普洱茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '801',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '799',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '808',
    'cat_name' => '基础营养',
    'measure_unit' => '',
    'parent_id' => '807',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '820',
    'cat_name' => '滋补养生',
    'measure_unit' => '',
    'parent_id' => '807',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '827',
    'cat_name' => '干果',
    'measure_unit' => '',
    'parent_id' => '807',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '818',
    'cat_name' => '葡萄籽',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '814',
    'cat_name' => '蛋白粉',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '816',
    'cat_name' => '左旋肉碱',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '812',
    'cat_name' => '膳食纤维',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '817',
    'cat_name' => '胶原蛋白',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '813',
    'cat_name' => '螺旋藻',
    'measure_unit' => '',
    'parent_id' => '808',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '825',
    'cat_name' => '更多滋补',
    'measure_unit' => '',
    'parent_id' => '820',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '822',
    'cat_name' => '阿胶',
    'measure_unit' => '',
    'parent_id' => '820',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '830',
    'cat_name' => '中老年',
    'measure_unit' => '',
    'parent_id' => '827',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '831',
    'cat_name' => '新疆大枣',
    'measure_unit' => '',
    'parent_id' => '827',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '828',
    'cat_name' => '成年女性',
    'measure_unit' => '',
    'parent_id' => '827',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '833',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '847',
    'cat_name' => '糕点/烘焙',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '843',
    'cat_name' => '曲奇/饼干',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '840',
    'cat_name' => '糖果/巧克力',
    'measure_unit' => '',
    'parent_id' => '832',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '838',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '833',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '836',
    'cat_name' => '蜜饯',
    'measure_unit' => '',
    'parent_id' => '833',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '837',
    'cat_name' => '肉类零食',
    'measure_unit' => '',
    'parent_id' => '833',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '841',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '840',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '842',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '840',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '844',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '843',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '845',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '843',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '853',
    'cat_name' => '沙琪玛',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '850',
    'cat_name' => '蛋卷/松塔',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '851',
    'cat_name' => '蛋糕/派',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '848',
    'cat_name' => '马卡龙',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '852',
    'cat_name' => '传统糕点',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '849',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '847',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '880',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '872',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '865',
    'cat_name' => '厨房调料',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '859',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '855',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '854',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '856',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '855',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '857',
    'cat_name' => '其他食用油',
    'measure_unit' => '',
    'parent_id' => '855',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '864',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '861',
    'cat_name' => '意大利面',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '862',
    'cat_name' => '面粉/面条',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '863',
    'cat_name' => '杂粮',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '860',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '859',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '870',
    'cat_name' => '果酱/涂抹酱',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '867',
    'cat_name' => '调味油/汁',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '868',
    'cat_name' => '调味料/粉/酱',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '869',
    'cat_name' => '底料/汤料',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '866',
    'cat_name' => '酱油/醋',
    'measure_unit' => '',
    'parent_id' => '865',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '876',
    'cat_name' => '干货礼盒',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '874',
    'cat_name' => '菜干',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '878',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '875',
    'cat_name' => '木耳/银耳',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '873',
    'cat_name' => '菌菇',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '879',
    'cat_name' => '海产干货',
    'measure_unit' => '',
    'parent_id' => '872',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '883',
    'cat_name' => '速食罐头',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '884',
    'cat_name' => '鱼子酱',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '881',
    'cat_name' => '速食面/汤',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '882',
    'cat_name' => '米粉/米线',
    'measure_unit' => '',
    'parent_id' => '880',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '909',
    'cat_name' => '水具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '886',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '902',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '894',
    'cat_name' => '厨房用具',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '915',
    'cat_name' => '婴儿喂养用品',
    'measure_unit' => '',
    'parent_id' => '885',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '892',
    'cat_name' => '烧水壶',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '889',
    'cat_name' => '汤锅/奶锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '893',
    'cat_name' => '砂锅/石锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '890',
    'cat_name' => '蒸锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '887',
    'cat_name' => '炒锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '891',
    'cat_name' => '锅具套装',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '888',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '886',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '899',
    'cat_name' => '烘焙用具',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  190 => 
  array (
    'cat_id' => '896',
    'cat_name' => '保鲜盒',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '900',
    'cat_name' => '清洁用具',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  192 => 
  array (
    'cat_id' => '897',
    'cat_name' => '密器罐/调味瓶',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '901',
    'cat_name' => '其他厨房配件',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '898',
    'cat_name' => '保鲜膜/袋',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '895',
    'cat_name' => '刀具',
    'measure_unit' => '',
    'parent_id' => '894',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  196 => 
  array (
    'cat_id' => '906',
    'cat_name' => '咖啡器具',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  197 => 
  array (
    'cat_id' => '907',
    'cat_name' => '烧烤用具',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  198 => 
  array (
    'cat_id' => '904',
    'cat_name' => '茶具/配件',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '903',
    'cat_name' => '碗/盘/碟/套装',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '908',
    'cat_name' => '其他餐具配件',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '905',
    'cat_name' => '酒具/配件',
    'measure_unit' => '',
    'parent_id' => '902',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  202 => 
  array (
    'cat_id' => '914',
    'cat_name' => '运动水壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  203 => 
  array (
    'cat_id' => '913',
    'cat_name' => '保温杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  204 => 
  array (
    'cat_id' => '912',
    'cat_name' => '陶瓷杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  205 => 
  array (
    'cat_id' => '910',
    'cat_name' => '塑料杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  206 => 
  array (
    'cat_id' => '911',
    'cat_name' => '玻璃杯/壶',
    'measure_unit' => '',
    'parent_id' => '909',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  207 => 
  array (
    'cat_id' => '916',
    'cat_name' => '奶瓶',
    'measure_unit' => '',
    'parent_id' => '915',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  208 => 
  array (
    'cat_id' => '919',
    'cat_name' => '宝宝餐具',
    'measure_unit' => '',
    'parent_id' => '915',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  209 => 
  array (
    'cat_id' => '920',
    'cat_name' => '其他辅助工具',
    'measure_unit' => '',
    'parent_id' => '915',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  210 => 
  array (
    'cat_id' => '931',
    'cat_name' => '辅食',
    'measure_unit' => '',
    'parent_id' => '921',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  211 => 
  array (
    'cat_id' => '922',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '921',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  212 => 
  array (
    'cat_id' => '939',
    'cat_name' => '营养品',
    'measure_unit' => '',
    'parent_id' => '921',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  213 => 
  array (
    'cat_id' => '928',
    'cat_name' => '四段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  214 => 
  array (
    'cat_id' => '925',
    'cat_name' => '一段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  215 => 
  array (
    'cat_id' => '929',
    'cat_name' => '特殊配方奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  216 => 
  array (
    'cat_id' => '926',
    'cat_name' => '二段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  217 => 
  array (
    'cat_id' => '923',
    'cat_name' => '国外有机奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  218 => 
  array (
    'cat_id' => '930',
    'cat_name' => '孕妇奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  219 => 
  array (
    'cat_id' => '927',
    'cat_name' => '三段奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  220 => 
  array (
    'cat_id' => '924',
    'cat_name' => '羊奶粉',
    'measure_unit' => '',
    'parent_id' => '922',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  221 => 
  array (
    'cat_id' => '934',
    'cat_name' => '面条类',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  222 => 
  array (
    'cat_id' => '938',
    'cat_name' => '宝宝零食',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  223 => 
  array (
    'cat_id' => '935',
    'cat_name' => '肉松/肉绒/肉酥',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  224 => 
  array (
    'cat_id' => '932',
    'cat_name' => '果泥/肉泥/菜泥',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  225 => 
  array (
    'cat_id' => '936',
    'cat_name' => '果汁/水/奶',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  226 => 
  array (
    'cat_id' => '933',
    'cat_name' => '米粉/米糊/冲调类',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  227 => 
  array (
    'cat_id' => '937',
    'cat_name' => '长牙期食品',
    'measure_unit' => '',
    'parent_id' => '931',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  228 => 
  array (
    'cat_id' => '947',
    'cat_name' => '孕产营养品',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  229 => 
  array (
    'cat_id' => '944',
    'cat_name' => '维生素/葡萄糖',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  230 => 
  array (
    'cat_id' => '941',
    'cat_name' => 'DHA',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  231 => 
  array (
    'cat_id' => '945',
    'cat_name' => '清火/开胃/伴侣',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  232 => 
  array (
    'cat_id' => '942',
    'cat_name' => '益生菌',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  233 => 
  array (
    'cat_id' => '946',
    'cat_name' => '孕婴食用油',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  234 => 
  array (
    'cat_id' => '943',
    'cat_name' => '鱼肝油',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  235 => 
  array (
    'cat_id' => '940',
    'cat_name' => '钙铁锌/乳铁蛋白/初乳',
    'measure_unit' => '',
    'parent_id' => '939',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  236 => 
  array (
    'cat_id' => '949',
    'cat_name' => '大枣',
    'measure_unit' => '',
    'parent_id' => '948',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>